// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.net.wifi.WifiManager$WpsCallback
// Destination: runtime/java/com/stratum/adapters/Adapter_android_net_wifi_WifiManager_WpsCallback.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_net_wifi_WifiManager_WpsCallback extends android.net.wifi.WifiManager.WpsCallback {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_net_wifi_WifiManager_WpsCallback(String key) {
        super();
        this.key_ = key;
    }

    @Override
    public void onFailed(int arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onFailed", new Object[]{ Integer.valueOf(arg0) });
    }

    @Override
    public void onStarted(String arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onStarted", new Object[]{ arg0 });
    }

    @Override
    public void onSucceeded() {
        StratumInvocationHandler.nativeDispatch(
            key_, "onSucceeded", new Object[0]);
    }

    @Override
    public String toString() {
        return "Adapter_android_net_wifi_WifiManager_WpsCallback[key=" + key_ + "]";
    }

}
