// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.view.WindowInsetsAnimation$Callback
// Destination: runtime/java/com/stratum/adapters/Adapter_android_view_WindowInsetsAnimation_Callback.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_view_WindowInsetsAnimation_Callback extends android.view.WindowInsetsAnimation.Callback {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_view_WindowInsetsAnimation_Callback(String key, int arg0) {
        super(arg0);
        this.key_ = key;
    }

    public Adapter_android_view_WindowInsetsAnimation_Callback(String key) {
        this(key, 0);
    }

    @Override
    public void onEnd(android.view.WindowInsetsAnimation arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onEnd", new Object[]{ arg0 });
    }

    @Override
    public void onPrepare(android.view.WindowInsetsAnimation arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onPrepare", new Object[]{ arg0 });
    }

    @Override
    public android.view.WindowInsets onProgress(android.view.WindowInsets arg0, java.util.List arg1) {
        Object __r = StratumInvocationHandler.nativeDispatch(
            key_, "onProgress", new Object[]{ arg0, arg1 });
        if (__r == null) { return null; }
        return (android.view.WindowInsets) __r;
    }

    @Override
    public android.view.WindowInsetsAnimation.Bounds onStart(android.view.WindowInsetsAnimation arg0, android.view.WindowInsetsAnimation.Bounds arg1) {
        Object __r = StratumInvocationHandler.nativeDispatch(
            key_, "onStart", new Object[]{ arg0, arg1 });
        if (__r == null) { return null; }
        return (android.view.WindowInsetsAnimation.Bounds) __r;
    }

    @Override
    public String toString() {
        return "Adapter_android_view_WindowInsetsAnimation_Callback[key=" + key_ + "]";
    }

}
