// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.media.MediaCodec$Callback
// Destination: runtime/java/com/stratum/adapters/Adapter_android_media_MediaCodec_Callback.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_media_MediaCodec_Callback extends android.media.MediaCodec.Callback {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_media_MediaCodec_Callback(String key) {
        super();
        this.key_ = key;
    }

    @Override
    public void onCryptoError(android.media.MediaCodec arg0, android.media.MediaCodec.CryptoException arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onCryptoError", new Object[]{ arg0, arg1 });
    }

    @Override
    public void onError(android.media.MediaCodec arg0, android.media.MediaCodec.CodecException arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onError", new Object[]{ arg0, arg1 });
    }

    @Override
    public void onInputBufferAvailable(android.media.MediaCodec arg0, int arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onInputBufferAvailable", new Object[]{ arg0, Integer.valueOf(arg1) });
    }

    @Override
    public void onOutputBufferAvailable(android.media.MediaCodec arg0, int arg1, android.media.MediaCodec.BufferInfo arg2) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onOutputBufferAvailable", new Object[]{ arg0, Integer.valueOf(arg1), arg2 });
    }

    @Override
    public void onOutputBuffersAvailable(android.media.MediaCodec arg0, int arg1, java.util.ArrayDeque arg2) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onOutputBuffersAvailable", new Object[]{ arg0, Integer.valueOf(arg1), arg2 });
    }

    @Override
    public void onOutputFormatChanged(android.media.MediaCodec arg0, android.media.MediaFormat arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onOutputFormatChanged", new Object[]{ arg0, arg1 });
    }

    @Override
    public String toString() {
        return "Adapter_android_media_MediaCodec_Callback[key=" + key_ + "]";
    }

}
