// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.media.MediaPlayer$OnErrorListener
// Destination: runtime/java/com/stratum/adapters/Adapter_android_media_MediaPlayer_OnErrorListener.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_media_MediaPlayer_OnErrorListener implements android.media.MediaPlayer.OnErrorListener {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_media_MediaPlayer_OnErrorListener(String key) {
        this.key_ = key;
    }

    @Override
    public boolean onError(android.media.MediaPlayer arg0, int arg1, int arg2) {
        Object __r = StratumInvocationHandler.nativeDispatch(
            key_, "onError", new Object[]{ arg0, Integer.valueOf(arg1), Integer.valueOf(arg2) });
        if (__r == null) { return false; }
        return (__r instanceof Boolean) ? ((Boolean) __r).booleanValue() : (__r instanceof Number && ((Number) __r).intValue() != 0);
    }

    @Override
    public String toString() {
        return "Adapter_android_media_MediaPlayer_OnErrorListener[key=" + key_ + "]";
    }

}
