// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.app.usage.NetworkStatsManager$UsageCallback
// Destination: runtime/java/com/stratum/adapters/Adapter_android_app_usage_NetworkStatsManager_UsageCallback.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_app_usage_NetworkStatsManager_UsageCallback extends android.app.usage.NetworkStatsManager.UsageCallback {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_app_usage_NetworkStatsManager_UsageCallback(String key) {
        super();
        this.key_ = key;
    }

    @Override
    public void onThresholdReached(int arg0, String arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onThresholdReached", new Object[]{ Integer.valueOf(arg0), arg1 });
    }

    @Override
    public String toString() {
        return "Adapter_android_app_usage_NetworkStatsManager_UsageCallback[key=" + key_ + "]";
    }

}
