// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.telephony.TelephonyManager$CellInfoCallback
// Destination: runtime/java/com/stratum/adapters/Adapter_android_telephony_TelephonyManager_CellInfoCallback.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_telephony_TelephonyManager_CellInfoCallback extends android.telephony.TelephonyManager.CellInfoCallback {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_telephony_TelephonyManager_CellInfoCallback(String key) {
        super();
        this.key_ = key;
    }

    @Override
    public void onCellInfo(java.util.List arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onCellInfo", new Object[]{ arg0 });
    }

    @Override
    public void onError(int arg0, Throwable arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onError", new Object[]{ Integer.valueOf(arg0), arg1 });
    }

    @Override
    public String toString() {
        return "Adapter_android_telephony_TelephonyManager_CellInfoCallback[key=" + key_ + "]";
    }

}
