// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.hardware.camera2.CameraExtensionSession$StateCallback
// Destination: runtime/java/com/stratum/adapters/Adapter_android_hardware_camera2_CameraExtensionSession_StateCallback.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_hardware_camera2_CameraExtensionSession_StateCallback extends android.hardware.camera2.CameraExtensionSession.StateCallback {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_hardware_camera2_CameraExtensionSession_StateCallback(String key) {
        super();
        this.key_ = key;
    }

    @Override
    public void onClosed(android.hardware.camera2.CameraExtensionSession arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onClosed", new Object[]{ arg0 });
    }

    @Override
    public void onConfigureFailed(android.hardware.camera2.CameraExtensionSession arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onConfigureFailed", new Object[]{ arg0 });
    }

    @Override
    public void onConfigured(android.hardware.camera2.CameraExtensionSession arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onConfigured", new Object[]{ arg0 });
    }

    @Override
    public String toString() {
        return "Adapter_android_hardware_camera2_CameraExtensionSession_StateCallback[key=" + key_ + "]";
    }

}
