// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.hardware.SensorEventListener
// Destination: runtime/java/com/stratum/adapters/Adapter_android_hardware_SensorEventListener.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_hardware_SensorEventListener implements android.hardware.SensorEventListener {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_hardware_SensorEventListener(String key) {
        this.key_ = key;
    }

    @Override
    public void onAccuracyChanged(android.hardware.Sensor arg0, int arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onAccuracyChanged", new Object[]{ arg0, Integer.valueOf(arg1) });
    }

    @Override
    public void onSensorChanged(android.hardware.SensorEvent arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onSensorChanged", new Object[]{ arg0 });
    }

    @Override
    public String toString() {
        return "Adapter_android_hardware_SensorEventListener[key=" + key_ + "]";
    }

}
