// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.media.MediaRecorder$OnErrorListener
// Destination: runtime/java/com/stratum/adapters/Adapter_android_media_MediaRecorder_OnErrorListener.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_media_MediaRecorder_OnErrorListener implements android.media.MediaRecorder.OnErrorListener {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_media_MediaRecorder_OnErrorListener(String key) {
        this.key_ = key;
    }

    @Override
    public void onError(android.media.MediaRecorder arg0, int arg1, int arg2) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onError", new Object[]{ arg0, Integer.valueOf(arg1), Integer.valueOf(arg2) });
    }

    @Override
    public String toString() {
        return "Adapter_android_media_MediaRecorder_OnErrorListener[key=" + key_ + "]";
    }

}
