// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.webkit.WebViewClient
// Destination: runtime/java/com/stratum/adapters/Adapter_android_webkit_WebViewClient.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_webkit_WebViewClient extends android.webkit.WebViewClient {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_webkit_WebViewClient(String key) {
        super();
        this.key_ = key;
    }

    @Override
    public void doUpdateVisitedHistory(android.webkit.WebView arg0, String arg1, boolean arg2) {
        StratumInvocationHandler.nativeDispatch(
            key_, "doUpdateVisitedHistory", new Object[]{ arg0, arg1, Boolean.valueOf(arg2) });
    }

    @Override
    public void onFormResubmission(android.webkit.WebView arg0, android.os.Message arg1, android.os.Message arg2) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onFormResubmission", new Object[]{ arg0, arg1, arg2 });
    }

    @Override
    public void onLoadResource(android.webkit.WebView arg0, String arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onLoadResource", new Object[]{ arg0, arg1 });
    }

    @Override
    public void onPageCommitVisible(android.webkit.WebView arg0, String arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onPageCommitVisible", new Object[]{ arg0, arg1 });
    }

    @Override
    public void onPageFinished(android.webkit.WebView arg0, String arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onPageFinished", new Object[]{ arg0, arg1 });
    }

    @Override
    public void onPageStarted(android.webkit.WebView arg0, String arg1, android.graphics.Bitmap arg2) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onPageStarted", new Object[]{ arg0, arg1, arg2 });
    }

    @Override
    public void onReceivedClientCertRequest(android.webkit.WebView arg0, android.webkit.ClientCertRequest arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onReceivedClientCertRequest", new Object[]{ arg0, arg1 });
    }

    @Override
    public void onReceivedError(android.webkit.WebView arg0, int arg1, String arg2, String arg3) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onReceivedError", new Object[]{ arg0, Integer.valueOf(arg1), arg2, arg3 });
    }

    @Override
    public void onReceivedError(android.webkit.WebView arg0, android.webkit.WebResourceRequest arg1, android.webkit.WebResourceError arg2) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onReceivedError", new Object[]{ arg0, arg1, arg2 });
    }

    @Override
    public void onReceivedHttpAuthRequest(android.webkit.WebView arg0, android.webkit.HttpAuthHandler arg1, String arg2, String arg3) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onReceivedHttpAuthRequest", new Object[]{ arg0, arg1, arg2, arg3 });
    }

    @Override
    public void onReceivedHttpError(android.webkit.WebView arg0, android.webkit.WebResourceRequest arg1, android.webkit.WebResourceResponse arg2) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onReceivedHttpError", new Object[]{ arg0, arg1, arg2 });
    }

    @Override
    public void onReceivedLoginRequest(android.webkit.WebView arg0, String arg1, String arg2, String arg3) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onReceivedLoginRequest", new Object[]{ arg0, arg1, arg2, arg3 });
    }

    @Override
    public void onReceivedSslError(android.webkit.WebView arg0, android.webkit.SslErrorHandler arg1, android.net.http.SslError arg2) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onReceivedSslError", new Object[]{ arg0, arg1, arg2 });
    }

    @Override
    public boolean onRenderProcessGone(android.webkit.WebView arg0, android.webkit.RenderProcessGoneDetail arg1) {
        Object __r = StratumInvocationHandler.nativeDispatch(
            key_, "onRenderProcessGone", new Object[]{ arg0, arg1 });
        if (__r == null) { return false; }
        return (__r instanceof Boolean) ? ((Boolean) __r).booleanValue() : (__r instanceof Number && ((Number) __r).intValue() != 0);
    }

    @Override
    public void onSafeBrowsingHit(android.webkit.WebView arg0, android.webkit.WebResourceRequest arg1, int arg2, android.webkit.SafeBrowsingResponse arg3) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onSafeBrowsingHit", new Object[]{ arg0, arg1, Integer.valueOf(arg2), arg3 });
    }

    @Override
    public void onScaleChanged(android.webkit.WebView arg0, float arg1, float arg2) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onScaleChanged", new Object[]{ arg0, Float.valueOf(arg1), Float.valueOf(arg2) });
    }

    @Override
    public void onTooManyRedirects(android.webkit.WebView arg0, android.os.Message arg1, android.os.Message arg2) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onTooManyRedirects", new Object[]{ arg0, arg1, arg2 });
    }

    @Override
    public void onUnhandledKeyEvent(android.webkit.WebView arg0, android.view.KeyEvent arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onUnhandledKeyEvent", new Object[]{ arg0, arg1 });
    }

    @Override
    public android.webkit.WebResourceResponse shouldInterceptRequest(android.webkit.WebView arg0, android.webkit.WebResourceRequest arg1) {
        Object __r = StratumInvocationHandler.nativeDispatch(
            key_, "shouldInterceptRequest", new Object[]{ arg0, arg1 });
        if (__r == null) { return null; }
        return (android.webkit.WebResourceResponse) __r;
    }

    @Override
    public android.webkit.WebResourceResponse shouldInterceptRequest(android.webkit.WebView arg0, String arg1) {
        Object __r = StratumInvocationHandler.nativeDispatch(
            key_, "shouldInterceptRequest", new Object[]{ arg0, arg1 });
        if (__r == null) { return null; }
        return (android.webkit.WebResourceResponse) __r;
    }

    @Override
    public boolean shouldOverrideKeyEvent(android.webkit.WebView arg0, android.view.KeyEvent arg1) {
        Object __r = StratumInvocationHandler.nativeDispatch(
            key_, "shouldOverrideKeyEvent", new Object[]{ arg0, arg1 });
        if (__r == null) { return false; }
        return (__r instanceof Boolean) ? ((Boolean) __r).booleanValue() : (__r instanceof Number && ((Number) __r).intValue() != 0);
    }

    @Override
    public boolean shouldOverrideUrlLoading(android.webkit.WebView arg0, android.webkit.WebResourceRequest arg1) {
        Object __r = StratumInvocationHandler.nativeDispatch(
            key_, "shouldOverrideUrlLoading", new Object[]{ arg0, arg1 });
        if (__r == null) { return false; }
        return (__r instanceof Boolean) ? ((Boolean) __r).booleanValue() : (__r instanceof Number && ((Number) __r).intValue() != 0);
    }

    @Override
    public boolean shouldOverrideUrlLoading(android.webkit.WebView arg0, String arg1) {
        Object __r = StratumInvocationHandler.nativeDispatch(
            key_, "shouldOverrideUrlLoading", new Object[]{ arg0, arg1 });
        if (__r == null) { return false; }
        return (__r instanceof Boolean) ? ((Boolean) __r).booleanValue() : (__r instanceof Number && ((Number) __r).intValue() != 0);
    }

    @Override
    public String toString() {
        return "Adapter_android_webkit_WebViewClient[key=" + key_ + "]";
    }

}
