// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.media.MediaSync$Callback
// Destination: runtime/java/com/stratum/adapters/Adapter_android_media_MediaSync_Callback.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_media_MediaSync_Callback extends android.media.MediaSync.Callback {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_media_MediaSync_Callback(String key) {
        super();
        this.key_ = key;
    }

    @Override
    public void onAudioBufferConsumed(android.media.MediaSync arg0, java.nio.ByteBuffer arg1, int arg2) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onAudioBufferConsumed", new Object[]{ arg0, arg1, Integer.valueOf(arg2) });
    }

    @Override
    public String toString() {
        return "Adapter_android_media_MediaSync_Callback[key=" + key_ + "]";
    }

}
