// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.hardware.camera2.CameraOfflineSession$CameraOfflineSessionCallback
// Destination: runtime/java/com/stratum/adapters/Adapter_android_hardware_camera2_CameraOfflineSession_CameraOfflineSessionCallback.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_hardware_camera2_CameraOfflineSession_CameraOfflineSessionCallback extends android.hardware.camera2.CameraOfflineSession.CameraOfflineSessionCallback {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_hardware_camera2_CameraOfflineSession_CameraOfflineSessionCallback(String key) {
        super();
        this.key_ = key;
    }

    @Override
    public void onClosed(android.hardware.camera2.CameraOfflineSession arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onClosed", new Object[]{ arg0 });
    }

    @Override
    public void onError(android.hardware.camera2.CameraOfflineSession arg0, int arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onError", new Object[]{ arg0, Integer.valueOf(arg1) });
    }

    @Override
    public void onIdle(android.hardware.camera2.CameraOfflineSession arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onIdle", new Object[]{ arg0 });
    }

    @Override
    public void onReady(android.hardware.camera2.CameraOfflineSession arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onReady", new Object[]{ arg0 });
    }

    @Override
    public void onSwitchFailed(android.hardware.camera2.CameraOfflineSession arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onSwitchFailed", new Object[]{ arg0 });
    }

    @Override
    public String toString() {
        return "Adapter_android_hardware_camera2_CameraOfflineSession_CameraOfflineSessionCallback[key=" + key_ + "]";
    }

}
