// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.content.DialogInterface$OnCancelListener
// Destination: runtime/java/com/stratum/adapters/Adapter_android_content_DialogInterface_OnCancelListener.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_content_DialogInterface_OnCancelListener implements android.content.DialogInterface.OnCancelListener {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_content_DialogInterface_OnCancelListener(String key) {
        this.key_ = key;
    }

    @Override
    public void onCancel(android.content.DialogInterface arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onCancel", new Object[]{ arg0 });
    }

    @Override
    public String toString() {
        return "Adapter_android_content_DialogInterface_OnCancelListener[key=" + key_ + "]";
    }

}
