// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.content.pm.LauncherApps$Callback
// Destination: runtime/java/com/stratum/adapters/Adapter_android_content_pm_LauncherApps_Callback.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_content_pm_LauncherApps_Callback extends android.content.pm.LauncherApps.Callback {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_content_pm_LauncherApps_Callback(String key) {
        super();
        this.key_ = key;
    }

    @Override
    public void onPackageAdded(String arg0, android.os.UserHandle arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onPackageAdded", new Object[]{ arg0, arg1 });
    }

    @Override
    public void onPackageChanged(String arg0, android.os.UserHandle arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onPackageChanged", new Object[]{ arg0, arg1 });
    }

    @Override
    public void onPackageLoadingProgressChanged(String arg0, android.os.UserHandle arg1, float arg2) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onPackageLoadingProgressChanged", new Object[]{ arg0, arg1, Float.valueOf(arg2) });
    }

    @Override
    public void onPackageRemoved(String arg0, android.os.UserHandle arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onPackageRemoved", new Object[]{ arg0, arg1 });
    }

    @Override
    public void onPackagesAvailable(String[] arg0, android.os.UserHandle arg1, boolean arg2) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onPackagesAvailable", new Object[]{ arg0, arg1, Boolean.valueOf(arg2) });
    }

    @Override
    public void onPackagesSuspended(String[] arg0, android.os.UserHandle arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onPackagesSuspended", new Object[]{ arg0, arg1 });
    }

    @Override
    public void onPackagesSuspended(String[] arg0, android.os.UserHandle arg1, android.os.Bundle arg2) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onPackagesSuspended", new Object[]{ arg0, arg1, arg2 });
    }

    @Override
    public void onPackagesUnavailable(String[] arg0, android.os.UserHandle arg1, boolean arg2) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onPackagesUnavailable", new Object[]{ arg0, arg1, Boolean.valueOf(arg2) });
    }

    @Override
    public void onPackagesUnsuspended(String[] arg0, android.os.UserHandle arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onPackagesUnsuspended", new Object[]{ arg0, arg1 });
    }

    @Override
    public void onShortcutsChanged(String arg0, java.util.List arg1, android.os.UserHandle arg2) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onShortcutsChanged", new Object[]{ arg0, arg1, arg2 });
    }

    @Override
    public String toString() {
        return "Adapter_android_content_pm_LauncherApps_Callback[key=" + key_ + "]";
    }

}
