// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.net.vcn.VcnManager$VcnStatusCallback
// Destination: runtime/java/com/stratum/adapters/Adapter_android_net_vcn_VcnManager_VcnStatusCallback.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_net_vcn_VcnManager_VcnStatusCallback extends android.net.vcn.VcnManager.VcnStatusCallback {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_net_vcn_VcnManager_VcnStatusCallback(String key) {
        super();
        this.key_ = key;
    }

    @Override
    public void onGatewayConnectionError(String arg0, int arg1, Throwable arg2) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onGatewayConnectionError", new Object[]{ arg0, Integer.valueOf(arg1), arg2 });
    }

    @Override
    public void onStatusChanged(int arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onStatusChanged", new Object[]{ Integer.valueOf(arg0) });
    }

    @Override
    public String toString() {
        return "Adapter_android_net_vcn_VcnManager_VcnStatusCallback[key=" + key_ + "]";
    }

}
