// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.webkit.ValueCallback
// Destination: runtime/java/com/stratum/adapters/Adapter_android_webkit_ValueCallback.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_webkit_ValueCallback implements android.webkit.ValueCallback {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_webkit_ValueCallback(String key) {
        this.key_ = key;
    }

    @Override
    public void onReceiveValue(Object arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onReceiveValue", new Object[]{ arg0 });
    }

    @Override
    public String toString() {
        return "Adapter_android_webkit_ValueCallback[key=" + key_ + "]";
    }

}
