// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.hardware.camera2.CameraDevice$StateCallback
// Destination: runtime/java/com/stratum/adapters/Adapter_android_hardware_camera2_CameraDevice_StateCallback.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_hardware_camera2_CameraDevice_StateCallback extends android.hardware.camera2.CameraDevice.StateCallback {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_hardware_camera2_CameraDevice_StateCallback(String key) {
        super();
        this.key_ = key;
    }

    @Override
    public void onClosed(android.hardware.camera2.CameraDevice arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onClosed", new Object[]{ arg0 });
    }

    @Override
    public void onDisconnected(android.hardware.camera2.CameraDevice arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onDisconnected", new Object[]{ arg0 });
    }

    @Override
    public void onError(android.hardware.camera2.CameraDevice arg0, int arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onError", new Object[]{ arg0, Integer.valueOf(arg1) });
    }

    @Override
    public void onOpened(android.hardware.camera2.CameraDevice arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onOpened", new Object[]{ arg0 });
    }

    @Override
    public String toString() {
        return "Adapter_android_hardware_camera2_CameraDevice_StateCallback[key=" + key_ + "]";
    }

}
