// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.hardware.camera2.CameraCaptureSession$CaptureCallback
// Destination: runtime/java/com/stratum/adapters/Adapter_android_hardware_camera2_CameraCaptureSession_CaptureCallback.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_hardware_camera2_CameraCaptureSession_CaptureCallback extends android.hardware.camera2.CameraCaptureSession.CaptureCallback {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_hardware_camera2_CameraCaptureSession_CaptureCallback(String key) {
        super();
        this.key_ = key;
    }

    @Override
    public void onCaptureBufferLost(android.hardware.camera2.CameraCaptureSession arg0, android.hardware.camera2.CaptureRequest arg1, android.view.Surface arg2, long arg3) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onCaptureBufferLost", new Object[]{ arg0, arg1, arg2, Long.valueOf(arg3) });
    }

    @Override
    public void onCaptureCompleted(android.hardware.camera2.CameraCaptureSession arg0, android.hardware.camera2.CaptureRequest arg1, android.hardware.camera2.TotalCaptureResult arg2) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onCaptureCompleted", new Object[]{ arg0, arg1, arg2 });
    }

    @Override
    public void onCaptureFailed(android.hardware.camera2.CameraCaptureSession arg0, android.hardware.camera2.CaptureRequest arg1, android.hardware.camera2.CaptureFailure arg2) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onCaptureFailed", new Object[]{ arg0, arg1, arg2 });
    }

    @Override
    public void onCaptureProgressed(android.hardware.camera2.CameraCaptureSession arg0, android.hardware.camera2.CaptureRequest arg1, android.hardware.camera2.CaptureResult arg2) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onCaptureProgressed", new Object[]{ arg0, arg1, arg2 });
    }

    @Override
    public void onCaptureSequenceAborted(android.hardware.camera2.CameraCaptureSession arg0, int arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onCaptureSequenceAborted", new Object[]{ arg0, Integer.valueOf(arg1) });
    }

    @Override
    public void onCaptureSequenceCompleted(android.hardware.camera2.CameraCaptureSession arg0, int arg1, long arg2) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onCaptureSequenceCompleted", new Object[]{ arg0, Integer.valueOf(arg1), Long.valueOf(arg2) });
    }

    @Override
    public void onCaptureStarted(android.hardware.camera2.CameraCaptureSession arg0, android.hardware.camera2.CaptureRequest arg1, long arg2, long arg3) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onCaptureStarted", new Object[]{ arg0, arg1, Long.valueOf(arg2), Long.valueOf(arg3) });
    }

    @Override
    public void onReadoutStarted(android.hardware.camera2.CameraCaptureSession arg0, android.hardware.camera2.CaptureRequest arg1, long arg2, long arg3) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onReadoutStarted", new Object[]{ arg0, arg1, Long.valueOf(arg2), Long.valueOf(arg3) });
    }

    @Override
    public String toString() {
        return "Adapter_android_hardware_camera2_CameraCaptureSession_CaptureCallback[key=" + key_ + "]";
    }

}
