// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.telephony.ims.ProvisioningManager$FeatureProvisioningCallback
// Destination: runtime/java/com/stratum/adapters/Adapter_android_telephony_ims_ProvisioningManager_FeatureProvisioningCallback.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_telephony_ims_ProvisioningManager_FeatureProvisioningCallback extends android.telephony.ims.ProvisioningManager.FeatureProvisioningCallback {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_telephony_ims_ProvisioningManager_FeatureProvisioningCallback(String key) {
        super();
        this.key_ = key;
    }

    @Override
    public void onFeatureProvisioningChanged(int arg0, int arg1, boolean arg2) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onFeatureProvisioningChanged", new Object[]{ Integer.valueOf(arg0), Integer.valueOf(arg1), Boolean.valueOf(arg2) });
    }

    @Override
    public void onRcsFeatureProvisioningChanged(int arg0, int arg1, boolean arg2) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onRcsFeatureProvisioningChanged", new Object[]{ Integer.valueOf(arg0), Integer.valueOf(arg1), Boolean.valueOf(arg2) });
    }

    @Override
    public String toString() {
        return "Adapter_android_telephony_ims_ProvisioningManager_FeatureProvisioningCallback[key=" + key_ + "]";
    }

}
