// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.view.TextureView$SurfaceTextureListener
// Destination: runtime/java/com/stratum/adapters/Adapter_android_view_TextureView_SurfaceTextureListener.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_view_TextureView_SurfaceTextureListener implements android.view.TextureView.SurfaceTextureListener {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_view_TextureView_SurfaceTextureListener(String key) {
        this.key_ = key;
    }

    @Override
    public void onSurfaceTextureAvailable(android.graphics.SurfaceTexture arg0, int arg1, int arg2) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onSurfaceTextureAvailable", new Object[]{ arg0, Integer.valueOf(arg1), Integer.valueOf(arg2) });
    }

    @Override
    public boolean onSurfaceTextureDestroyed(android.graphics.SurfaceTexture arg0) {
        Object __r = StratumInvocationHandler.nativeDispatch(
            key_, "onSurfaceTextureDestroyed", new Object[]{ arg0 });
        if (__r == null) { return false; }
        return (__r instanceof Boolean) ? ((Boolean) __r).booleanValue() : (__r instanceof Number && ((Number) __r).intValue() != 0);
    }

    @Override
    public void onSurfaceTextureSizeChanged(android.graphics.SurfaceTexture arg0, int arg1, int arg2) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onSurfaceTextureSizeChanged", new Object[]{ arg0, Integer.valueOf(arg1), Integer.valueOf(arg2) });
    }

    @Override
    public void onSurfaceTextureUpdated(android.graphics.SurfaceTexture arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onSurfaceTextureUpdated", new Object[]{ arg0 });
    }

    @Override
    public String toString() {
        return "Adapter_android_view_TextureView_SurfaceTextureListener[key=" + key_ + "]";
    }

}
