// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.webkit.WebChromeClient
// Destination: runtime/java/com/stratum/adapters/Adapter_android_webkit_WebChromeClient.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_webkit_WebChromeClient extends android.webkit.WebChromeClient {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_webkit_WebChromeClient(String key) {
        super();
        this.key_ = key;
    }

    @Override
    public android.graphics.Bitmap getDefaultVideoPoster() {
        Object __r = StratumInvocationHandler.nativeDispatch(
            key_, "getDefaultVideoPoster", new Object[0]);
        if (__r == null) { return null; }
        return (android.graphics.Bitmap) __r;
    }

    @Override
    public android.view.View getVideoLoadingProgressView() {
        Object __r = StratumInvocationHandler.nativeDispatch(
            key_, "getVideoLoadingProgressView", new Object[0]);
        if (__r == null) { return null; }
        return (android.view.View) __r;
    }

    @Override
    public void getVisitedHistory(android.webkit.ValueCallback arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "getVisitedHistory", new Object[]{ arg0 });
    }

    @Override
    public void onCloseWindow(android.webkit.WebView arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onCloseWindow", new Object[]{ arg0 });
    }

    @Override
    public boolean onConsoleMessage(android.webkit.ConsoleMessage arg0) {
        Object __r = StratumInvocationHandler.nativeDispatch(
            key_, "onConsoleMessage", new Object[]{ arg0 });
        if (__r == null) { return false; }
        return (__r instanceof Boolean) ? ((Boolean) __r).booleanValue() : (__r instanceof Number && ((Number) __r).intValue() != 0);
    }

    @Override
    public void onConsoleMessage(String arg0, int arg1, String arg2) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onConsoleMessage", new Object[]{ arg0, Integer.valueOf(arg1), arg2 });
    }

    @Override
    public boolean onCreateWindow(android.webkit.WebView arg0, boolean arg1, boolean arg2, android.os.Message arg3) {
        Object __r = StratumInvocationHandler.nativeDispatch(
            key_, "onCreateWindow", new Object[]{ arg0, Boolean.valueOf(arg1), Boolean.valueOf(arg2), arg3 });
        if (__r == null) { return false; }
        return (__r instanceof Boolean) ? ((Boolean) __r).booleanValue() : (__r instanceof Number && ((Number) __r).intValue() != 0);
    }

    @Override
    public void onExceededDatabaseQuota(String arg0, String arg1, long arg2, long arg3, long arg4, android.webkit.WebStorage.QuotaUpdater arg5) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onExceededDatabaseQuota", new Object[]{ arg0, arg1, Long.valueOf(arg2), Long.valueOf(arg3), Long.valueOf(arg4), arg5 });
    }

    @Override
    public void onGeolocationPermissionsHidePrompt() {
        StratumInvocationHandler.nativeDispatch(
            key_, "onGeolocationPermissionsHidePrompt", new Object[0]);
    }

    @Override
    public void onGeolocationPermissionsShowPrompt(String arg0, android.webkit.GeolocationPermissions.Callback arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onGeolocationPermissionsShowPrompt", new Object[]{ arg0, arg1 });
    }

    @Override
    public void onHideCustomView() {
        StratumInvocationHandler.nativeDispatch(
            key_, "onHideCustomView", new Object[0]);
    }

    @Override
    public boolean onJsAlert(android.webkit.WebView arg0, String arg1, String arg2, android.webkit.JsResult arg3) {
        Object __r = StratumInvocationHandler.nativeDispatch(
            key_, "onJsAlert", new Object[]{ arg0, arg1, arg2, arg3 });
        if (__r == null) { return false; }
        return (__r instanceof Boolean) ? ((Boolean) __r).booleanValue() : (__r instanceof Number && ((Number) __r).intValue() != 0);
    }

    @Override
    public boolean onJsBeforeUnload(android.webkit.WebView arg0, String arg1, String arg2, android.webkit.JsResult arg3) {
        Object __r = StratumInvocationHandler.nativeDispatch(
            key_, "onJsBeforeUnload", new Object[]{ arg0, arg1, arg2, arg3 });
        if (__r == null) { return false; }
        return (__r instanceof Boolean) ? ((Boolean) __r).booleanValue() : (__r instanceof Number && ((Number) __r).intValue() != 0);
    }

    @Override
    public boolean onJsConfirm(android.webkit.WebView arg0, String arg1, String arg2, android.webkit.JsResult arg3) {
        Object __r = StratumInvocationHandler.nativeDispatch(
            key_, "onJsConfirm", new Object[]{ arg0, arg1, arg2, arg3 });
        if (__r == null) { return false; }
        return (__r instanceof Boolean) ? ((Boolean) __r).booleanValue() : (__r instanceof Number && ((Number) __r).intValue() != 0);
    }

    @Override
    public boolean onJsPrompt(android.webkit.WebView arg0, String arg1, String arg2, String arg3, android.webkit.JsPromptResult arg4) {
        Object __r = StratumInvocationHandler.nativeDispatch(
            key_, "onJsPrompt", new Object[]{ arg0, arg1, arg2, arg3, arg4 });
        if (__r == null) { return false; }
        return (__r instanceof Boolean) ? ((Boolean) __r).booleanValue() : (__r instanceof Number && ((Number) __r).intValue() != 0);
    }

    @Override
    public boolean onJsTimeout() {
        Object __r = StratumInvocationHandler.nativeDispatch(
            key_, "onJsTimeout", new Object[0]);
        if (__r == null) { return false; }
        return (__r instanceof Boolean) ? ((Boolean) __r).booleanValue() : (__r instanceof Number && ((Number) __r).intValue() != 0);
    }

    @Override
    public void onPermissionRequest(android.webkit.PermissionRequest arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onPermissionRequest", new Object[]{ arg0 });
    }

    @Override
    public void onPermissionRequestCanceled(android.webkit.PermissionRequest arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onPermissionRequestCanceled", new Object[]{ arg0 });
    }

    @Override
    public void onProgressChanged(android.webkit.WebView arg0, int arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onProgressChanged", new Object[]{ arg0, Integer.valueOf(arg1) });
    }

    @Override
    public void onReceivedIcon(android.webkit.WebView arg0, android.graphics.Bitmap arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onReceivedIcon", new Object[]{ arg0, arg1 });
    }

    @Override
    public void onReceivedTitle(android.webkit.WebView arg0, String arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onReceivedTitle", new Object[]{ arg0, arg1 });
    }

    @Override
    public void onReceivedTouchIconUrl(android.webkit.WebView arg0, String arg1, boolean arg2) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onReceivedTouchIconUrl", new Object[]{ arg0, arg1, Boolean.valueOf(arg2) });
    }

    @Override
    public void onRequestFocus(android.webkit.WebView arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onRequestFocus", new Object[]{ arg0 });
    }

    @Override
    public void onShowCustomView(android.view.View arg0, int arg1, android.webkit.WebChromeClient.CustomViewCallback arg2) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onShowCustomView", new Object[]{ arg0, Integer.valueOf(arg1), arg2 });
    }

    @Override
    public void onShowCustomView(android.view.View arg0, android.webkit.WebChromeClient.CustomViewCallback arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onShowCustomView", new Object[]{ arg0, arg1 });
    }

    @Override
    public boolean onShowFileChooser(android.webkit.WebView arg0, android.webkit.ValueCallback arg1, android.webkit.WebChromeClient.FileChooserParams arg2) {
        Object __r = StratumInvocationHandler.nativeDispatch(
            key_, "onShowFileChooser", new Object[]{ arg0, arg1, arg2 });
        if (__r == null) { return false; }
        return (__r instanceof Boolean) ? ((Boolean) __r).booleanValue() : (__r instanceof Number && ((Number) __r).intValue() != 0);
    }

    @Override
    public String toString() {
        return "Adapter_android_webkit_WebChromeClient[key=" + key_ + "]";
    }

}
