// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.content.pm.PackageInstaller$SessionCallback
// Destination: runtime/java/com/stratum/adapters/Adapter_android_content_pm_PackageInstaller_SessionCallback.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_content_pm_PackageInstaller_SessionCallback extends android.content.pm.PackageInstaller.SessionCallback {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_content_pm_PackageInstaller_SessionCallback(String key) {
        super();
        this.key_ = key;
    }

    @Override
    public void onActiveChanged(int arg0, boolean arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onActiveChanged", new Object[]{ Integer.valueOf(arg0), Boolean.valueOf(arg1) });
    }

    @Override
    public void onBadgingChanged(int arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onBadgingChanged", new Object[]{ Integer.valueOf(arg0) });
    }

    @Override
    public void onCreated(int arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onCreated", new Object[]{ Integer.valueOf(arg0) });
    }

    @Override
    public void onFinished(int arg0, boolean arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onFinished", new Object[]{ Integer.valueOf(arg0), Boolean.valueOf(arg1) });
    }

    @Override
    public void onProgressChanged(int arg0, float arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onProgressChanged", new Object[]{ Integer.valueOf(arg0), Float.valueOf(arg1) });
    }

    @Override
    public String toString() {
        return "Adapter_android_content_pm_PackageInstaller_SessionCallback[key=" + key_ + "]";
    }

}
