// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.hardware.TriggerEventListener
// Destination: runtime/java/com/stratum/adapters/Adapter_android_hardware_TriggerEventListener.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_hardware_TriggerEventListener extends android.hardware.TriggerEventListener {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_hardware_TriggerEventListener(String key) {
        super();
        this.key_ = key;
    }

    @Override
    public void onTrigger(android.hardware.TriggerEvent arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onTrigger", new Object[]{ arg0 });
    }

    @Override
    public String toString() {
        return "Adapter_android_hardware_TriggerEventListener[key=" + key_ + "]";
    }

}
