// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.webkit.WebViewRenderProcessClient
// Destination: runtime/java/com/stratum/adapters/Adapter_android_webkit_WebViewRenderProcessClient.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_webkit_WebViewRenderProcessClient extends android.webkit.WebViewRenderProcessClient {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_webkit_WebViewRenderProcessClient(String key) {
        super();
        this.key_ = key;
    }

    @Override
    public void onRenderProcessResponsive(android.webkit.WebView arg0, android.webkit.WebViewRenderProcess arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onRenderProcessResponsive", new Object[]{ arg0, arg1 });
    }

    @Override
    public void onRenderProcessUnresponsive(android.webkit.WebView arg0, android.webkit.WebViewRenderProcess arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onRenderProcessUnresponsive", new Object[]{ arg0, arg1 });
    }

    @Override
    public String toString() {
        return "Adapter_android_webkit_WebViewRenderProcessClient[key=" + key_ + "]";
    }

}
