// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.view.WindowId$FocusObserver
// Destination: runtime/java/com/stratum/adapters/Adapter_android_view_WindowId_FocusObserver.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_view_WindowId_FocusObserver extends android.view.WindowId.FocusObserver {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_view_WindowId_FocusObserver(String key) {
        super();
        this.key_ = key;
    }

    @Override
    public void onFocusGained(android.view.WindowId arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onFocusGained", new Object[]{ arg0 });
    }

    @Override
    public void onFocusLost(android.view.WindowId arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onFocusLost", new Object[]{ arg0 });
    }

    @Override
    public String toString() {
        return "Adapter_android_view_WindowId_FocusObserver[key=" + key_ + "]";
    }

}
