// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.net.wifi.WifiManager$SubsystemRestartTrackingCallback
// Destination: runtime/java/com/stratum/adapters/Adapter_android_net_wifi_WifiManager_SubsystemRestartTrackingCallback.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_net_wifi_WifiManager_SubsystemRestartTrackingCallback extends android.net.wifi.WifiManager.SubsystemRestartTrackingCallback {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_net_wifi_WifiManager_SubsystemRestartTrackingCallback(String key) {
        super();
        this.key_ = key;
    }

    @Override
    public void onSubsystemRestarted() {
        StratumInvocationHandler.nativeDispatch(
            key_, "onSubsystemRestarted", new Object[0]);
    }

    @Override
    public void onSubsystemRestarting() {
        StratumInvocationHandler.nativeDispatch(
            key_, "onSubsystemRestarting", new Object[0]);
    }

    @Override
    public String toString() {
        return "Adapter_android_net_wifi_WifiManager_SubsystemRestartTrackingCallback[key=" + key_ + "]";
    }

}
