// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.widget.AdapterView$OnItemSelectedListener
// Destination: runtime/java/com/stratum/adapters/Adapter_android_widget_AdapterView_OnItemSelectedListener.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_widget_AdapterView_OnItemSelectedListener implements android.widget.AdapterView.OnItemSelectedListener {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_widget_AdapterView_OnItemSelectedListener(String key) {
        this.key_ = key;
    }

    @Override
    public void onItemSelected(android.widget.AdapterView arg0, android.view.View arg1, int arg2, long arg3) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onItemSelected", new Object[]{ arg0, arg1, Integer.valueOf(arg2), Long.valueOf(arg3) });
    }

    @Override
    public void onNothingSelected(android.widget.AdapterView arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onNothingSelected", new Object[]{ arg0 });
    }

    @Override
    public String toString() {
        return "Adapter_android_widget_AdapterView_OnItemSelectedListener[key=" + key_ + "]";
    }

}
