// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.net.wifi.rtt.RangingResultCallback
// Destination: runtime/java/com/stratum/adapters/Adapter_android_net_wifi_rtt_RangingResultCallback.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_net_wifi_rtt_RangingResultCallback extends android.net.wifi.rtt.RangingResultCallback {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_net_wifi_rtt_RangingResultCallback(String key) {
        super();
        this.key_ = key;
    }

    @Override
    public void onRangingFailure(int arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onRangingFailure", new Object[]{ Integer.valueOf(arg0) });
    }

    @Override
    public void onRangingResults(java.util.List arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onRangingResults", new Object[]{ arg0 });
    }

    @Override
    public String toString() {
        return "Adapter_android_net_wifi_rtt_RangingResultCallback[key=" + key_ + "]";
    }

}
