// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.content.DialogInterface$OnClickListener
// Destination: runtime/java/com/stratum/adapters/Adapter_android_content_DialogInterface_OnClickListener.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_content_DialogInterface_OnClickListener implements android.content.DialogInterface.OnClickListener {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_content_DialogInterface_OnClickListener(String key) {
        this.key_ = key;
    }

    @Override
    public void onClick(android.content.DialogInterface arg0, int arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onClick", new Object[]{ arg0, Integer.valueOf(arg1) });
    }

    @Override
    public String toString() {
        return "Adapter_android_content_DialogInterface_OnClickListener[key=" + key_ + "]";
    }

}
