// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.os.ProxyFileDescriptorCallback
// Destination: runtime/java/com/stratum/adapters/Adapter_android_os_ProxyFileDescriptorCallback.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_os_ProxyFileDescriptorCallback extends android.os.ProxyFileDescriptorCallback {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_os_ProxyFileDescriptorCallback(String key) {
        super();
        this.key_ = key;
    }

    @Override
    public void onFsync() {
        StratumInvocationHandler.nativeDispatch(
            key_, "onFsync", new Object[0]);
    }

    @Override
    public long onGetSize() {
        Object __r = StratumInvocationHandler.nativeDispatch(
            key_, "onGetSize", new Object[0]);
        if (__r == null) { return 0L; }
        return ((Long) __r).longValue();
    }

    @Override
    public int onRead(long arg0, int arg1, byte[] arg2) {
        Object __r = StratumInvocationHandler.nativeDispatch(
            key_, "onRead", new Object[]{ Long.valueOf(arg0), Integer.valueOf(arg1), arg2 });
        if (__r == null) { return 0; }
        return ((Integer) __r).intValue();
    }

    @Override
    public void onRelease() {
        StratumInvocationHandler.nativeDispatch(
            key_, "onRelease", new Object[0]);
    }

    @Override
    public int onWrite(long arg0, int arg1, byte[] arg2) {
        Object __r = StratumInvocationHandler.nativeDispatch(
            key_, "onWrite", new Object[]{ Long.valueOf(arg0), Integer.valueOf(arg1), arg2 });
        if (__r == null) { return 0; }
        return ((Integer) __r).intValue();
    }

    @Override
    public String toString() {
        return "Adapter_android_os_ProxyFileDescriptorCallback[key=" + key_ + "]";
    }

}
