// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.widget.Filter
// Destination: runtime/java/com/stratum/adapters/Adapter_android_widget_Filter.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_widget_Filter extends android.widget.Filter {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_widget_Filter(String key) {
        super();
        this.key_ = key;
    }

    @Override
    public CharSequence convertResultToString(Object arg0) {
        Object __r = StratumInvocationHandler.nativeDispatch(
            key_, "convertResultToString", new Object[]{ arg0 });
        if (__r == null) { return null; }
        return (CharSequence) __r;
    }

    @Override
    public android.widget.Filter.FilterResults performFiltering(CharSequence arg0) {
        Object __r = StratumInvocationHandler.nativeDispatch(
            key_, "performFiltering", new Object[]{ arg0 });
        if (__r == null) { return null; }
        return (android.widget.Filter.FilterResults) __r;
    }

    @Override
    public void publishResults(CharSequence arg0, android.widget.Filter.FilterResults arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "publishResults", new Object[]{ arg0, arg1 });
    }

    @Override
    public String toString() {
        return "Adapter_android_widget_Filter[key=" + key_ + "]";
    }

}
