// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.view.OrientationEventListener
// Destination: runtime/java/com/stratum/adapters/Adapter_android_view_OrientationEventListener.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_view_OrientationEventListener extends android.view.OrientationEventListener {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_view_OrientationEventListener(String key, android.content.Context arg0) {
        super(arg0);
        this.key_ = key;
    }

    public Adapter_android_view_OrientationEventListener(String key) {
        this(key, null);
    }

    @Override
    public boolean canDetectOrientation() {
        Object __r = StratumInvocationHandler.nativeDispatch(
            key_, "canDetectOrientation", new Object[0]);
        if (__r == null) { return false; }
        return (__r instanceof Boolean) ? ((Boolean) __r).booleanValue() : (__r instanceof Number && ((Number) __r).intValue() != 0);
    }

    @Override
    public void disable() {
        StratumInvocationHandler.nativeDispatch(
            key_, "disable", new Object[0]);
    }

    @Override
    public void enable() {
        StratumInvocationHandler.nativeDispatch(
            key_, "enable", new Object[0]);
    }

    @Override
    public void onOrientationChanged(int arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onOrientationChanged", new Object[]{ Integer.valueOf(arg0) });
    }

    @Override
    public String toString() {
        return "Adapter_android_view_OrientationEventListener[key=" + key_ + "]";
    }

}
