// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.media.MediaPlayer$OnPreparedListener
// Destination: runtime/java/com/stratum/adapters/Adapter_android_media_MediaPlayer_OnPreparedListener.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_media_MediaPlayer_OnPreparedListener implements android.media.MediaPlayer.OnPreparedListener {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_media_MediaPlayer_OnPreparedListener(String key) {
        this.key_ = key;
    }

    @Override
    public void onPrepared(android.media.MediaPlayer arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onPrepared", new Object[]{ arg0 });
    }

    @Override
    public String toString() {
        return "Adapter_android_media_MediaPlayer_OnPreparedListener[key=" + key_ + "]";
    }

}
