// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.location.GnssMeasurementsEvent$Callback
// Destination: runtime/java/com/stratum/adapters/Adapter_android_location_GnssMeasurementsEvent_Callback.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_location_GnssMeasurementsEvent_Callback extends android.location.GnssMeasurementsEvent.Callback {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_location_GnssMeasurementsEvent_Callback(String key) {
        super();
        this.key_ = key;
    }

    @Override
    public void onGnssMeasurementsReceived(android.location.GnssMeasurementsEvent arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onGnssMeasurementsReceived", new Object[]{ arg0 });
    }

    @Override
    public void onStatusChanged(int arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onStatusChanged", new Object[]{ Integer.valueOf(arg0) });
    }

    @Override
    public String toString() {
        return "Adapter_android_location_GnssMeasurementsEvent_Callback[key=" + key_ + "]";
    }

}
