// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.os.FileObserver
// Destination: runtime/java/com/stratum/adapters/Adapter_android_os_FileObserver.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_os_FileObserver extends android.os.FileObserver {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_os_FileObserver(String key, java.io.File arg0) {
        super(arg0);
        this.key_ = key;
    }

    public Adapter_android_os_FileObserver(String key) {
        this(key, null);
    }

    @Override
    public void onEvent(int arg0, String arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onEvent", new Object[]{ Integer.valueOf(arg0), arg1 });
    }

    @Override
    public void startWatching() {
        StratumInvocationHandler.nativeDispatch(
            key_, "startWatching", new Object[0]);
    }

    @Override
    public void stopWatching() {
        StratumInvocationHandler.nativeDispatch(
            key_, "stopWatching", new Object[0]);
    }

    @Override
    public String toString() {
        return "Adapter_android_os_FileObserver[key=" + key_ + "]";
    }

}
