// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.app.AppOpsManager$OnOpNotedCallback
// Destination: runtime/java/com/stratum/adapters/Adapter_android_app_AppOpsManager_OnOpNotedCallback.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_app_AppOpsManager_OnOpNotedCallback extends android.app.AppOpsManager.OnOpNotedCallback {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_app_AppOpsManager_OnOpNotedCallback(String key) {
        super();
        this.key_ = key;
    }

    @Override
    public void onAsyncNoted(android.app.AsyncNotedAppOp arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onAsyncNoted", new Object[]{ arg0 });
    }

    @Override
    public void onNoted(android.app.SyncNotedAppOp arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onNoted", new Object[]{ arg0 });
    }

    @Override
    public void onSelfNoted(android.app.SyncNotedAppOp arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onSelfNoted", new Object[]{ arg0 });
    }

    @Override
    public String toString() {
        return "Adapter_android_app_AppOpsManager_OnOpNotedCallback[key=" + key_ + "]";
    }

}
