// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.telephony.ims.ImsStateCallback
// Destination: runtime/java/com/stratum/adapters/Adapter_android_telephony_ims_ImsStateCallback.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_telephony_ims_ImsStateCallback extends android.telephony.ims.ImsStateCallback {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_telephony_ims_ImsStateCallback(String key) {
        super();
        this.key_ = key;
    }

    @Override
    public void onAvailable() {
        StratumInvocationHandler.nativeDispatch(
            key_, "onAvailable", new Object[0]);
    }

    @Override
    public void onError() {
        StratumInvocationHandler.nativeDispatch(
            key_, "onError", new Object[0]);
    }

    @Override
    public void onUnavailable(int arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onUnavailable", new Object[]{ Integer.valueOf(arg0) });
    }

    @Override
    public String toString() {
        return "Adapter_android_telephony_ims_ImsStateCallback[key=" + key_ + "]";
    }

}
