// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.webkit.WebView$VisualStateCallback
// Destination: runtime/java/com/stratum/adapters/Adapter_android_webkit_WebView_VisualStateCallback.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_webkit_WebView_VisualStateCallback extends android.webkit.WebView.VisualStateCallback {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_webkit_WebView_VisualStateCallback(String key) {
        super();
        this.key_ = key;
    }

    @Override
    public void onComplete(long arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onComplete", new Object[]{ Long.valueOf(arg0) });
    }

    @Override
    public String toString() {
        return "Adapter_android_webkit_WebView_VisualStateCallback[key=" + key_ + "]";
    }

}
