// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.speech.tts.UtteranceProgressListener
// Destination: runtime/java/com/stratum/adapters/Adapter_android_speech_tts_UtteranceProgressListener.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_speech_tts_UtteranceProgressListener extends android.speech.tts.UtteranceProgressListener {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_speech_tts_UtteranceProgressListener(String key) {
        super();
        this.key_ = key;
    }

    @Override
    public void onAudioAvailable(String arg0, byte[] arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onAudioAvailable", new Object[]{ arg0, arg1 });
    }

    @Override
    public void onBeginSynthesis(String arg0, int arg1, int arg2, int arg3) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onBeginSynthesis", new Object[]{ arg0, Integer.valueOf(arg1), Integer.valueOf(arg2), Integer.valueOf(arg3) });
    }

    @Override
    public void onDone(String arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onDone", new Object[]{ arg0 });
    }

    @Override
    public void onError(String arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onError", new Object[]{ arg0 });
    }

    @Override
    public void onError(String arg0, int arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onError", new Object[]{ arg0, Integer.valueOf(arg1) });
    }

    @Override
    public void onRangeStart(String arg0, int arg1, int arg2, int arg3) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onRangeStart", new Object[]{ arg0, Integer.valueOf(arg1), Integer.valueOf(arg2), Integer.valueOf(arg3) });
    }

    @Override
    public void onStart(String arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onStart", new Object[]{ arg0 });
    }

    @Override
    public void onStop(String arg0, boolean arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onStop", new Object[]{ arg0, Boolean.valueOf(arg1) });
    }

    @Override
    public String toString() {
        return "Adapter_android_speech_tts_UtteranceProgressListener[key=" + key_ + "]";
    }

}
