// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.media.MediaRouter$Callback
// Destination: runtime/java/com/stratum/adapters/Adapter_android_media_MediaRouter_Callback.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_media_MediaRouter_Callback extends android.media.MediaRouter.Callback {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_media_MediaRouter_Callback(String key) {
        super();
        this.key_ = key;
    }

    @Override
    public void onRouteAdded(android.media.MediaRouter arg0, android.media.MediaRouter.RouteInfo arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onRouteAdded", new Object[]{ arg0, arg1 });
    }

    @Override
    public void onRouteChanged(android.media.MediaRouter arg0, android.media.MediaRouter.RouteInfo arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onRouteChanged", new Object[]{ arg0, arg1 });
    }

    @Override
    public void onRouteGrouped(android.media.MediaRouter arg0, android.media.MediaRouter.RouteInfo arg1, android.media.MediaRouter.RouteGroup arg2, int arg3) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onRouteGrouped", new Object[]{ arg0, arg1, arg2, Integer.valueOf(arg3) });
    }

    @Override
    public void onRoutePresentationDisplayChanged(android.media.MediaRouter arg0, android.media.MediaRouter.RouteInfo arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onRoutePresentationDisplayChanged", new Object[]{ arg0, arg1 });
    }

    @Override
    public void onRouteRemoved(android.media.MediaRouter arg0, android.media.MediaRouter.RouteInfo arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onRouteRemoved", new Object[]{ arg0, arg1 });
    }

    @Override
    public void onRouteSelected(android.media.MediaRouter arg0, int arg1, android.media.MediaRouter.RouteInfo arg2) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onRouteSelected", new Object[]{ arg0, Integer.valueOf(arg1), arg2 });
    }

    @Override
    public void onRouteUngrouped(android.media.MediaRouter arg0, android.media.MediaRouter.RouteInfo arg1, android.media.MediaRouter.RouteGroup arg2) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onRouteUngrouped", new Object[]{ arg0, arg1, arg2 });
    }

    @Override
    public void onRouteUnselected(android.media.MediaRouter arg0, int arg1, android.media.MediaRouter.RouteInfo arg2) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onRouteUnselected", new Object[]{ arg0, Integer.valueOf(arg1), arg2 });
    }

    @Override
    public void onRouteVolumeChanged(android.media.MediaRouter arg0, android.media.MediaRouter.RouteInfo arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onRouteVolumeChanged", new Object[]{ arg0, arg1 });
    }

    @Override
    public String toString() {
        return "Adapter_android_media_MediaRouter_Callback[key=" + key_ + "]";
    }

}
