// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.view.OrientationListener
// Destination: runtime/java/com/stratum/adapters/Adapter_android_view_OrientationListener.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_view_OrientationListener extends android.view.OrientationListener {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_view_OrientationListener(String key, android.content.Context arg0) {
        super(arg0);
        this.key_ = key;
    }

    public Adapter_android_view_OrientationListener(String key) {
        this(key, null);
    }

    @Override
    public void disable() {
        StratumInvocationHandler.nativeDispatch(
            key_, "disable", new Object[0]);
    }

    @Override
    public void enable() {
        StratumInvocationHandler.nativeDispatch(
            key_, "enable", new Object[0]);
    }

    @Override
    public void onAccuracyChanged(int arg0, int arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onAccuracyChanged", new Object[]{ Integer.valueOf(arg0), Integer.valueOf(arg1) });
    }

    @Override
    public void onOrientationChanged(int arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onOrientationChanged", new Object[]{ Integer.valueOf(arg0) });
    }

    @Override
    public void onSensorChanged(int arg0, float[] arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onSensorChanged", new Object[]{ Integer.valueOf(arg0), arg1 });
    }

    @Override
    public String toString() {
        return "Adapter_android_view_OrientationListener[key=" + key_ + "]";
    }

}
