// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.media.MediaRouter$VolumeCallback
// Destination: runtime/java/com/stratum/adapters/Adapter_android_media_MediaRouter_VolumeCallback.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_media_MediaRouter_VolumeCallback extends android.media.MediaRouter.VolumeCallback {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_media_MediaRouter_VolumeCallback(String key) {
        super();
        this.key_ = key;
    }

    @Override
    public void onVolumeSetRequest(android.media.MediaRouter.RouteInfo arg0, int arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onVolumeSetRequest", new Object[]{ arg0, Integer.valueOf(arg1) });
    }

    @Override
    public void onVolumeUpdateRequest(android.media.MediaRouter.RouteInfo arg0, int arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onVolumeUpdateRequest", new Object[]{ arg0, Integer.valueOf(arg1) });
    }

    @Override
    public String toString() {
        return "Adapter_android_media_MediaRouter_VolumeCallback[key=" + key_ + "]";
    }

}
