// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.telecom.InCallService$VideoCall$Callback
// Destination: runtime/java/com/stratum/adapters/Adapter_android_telecom_InCallService_VideoCall_Callback.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_telecom_InCallService_VideoCall_Callback extends android.telecom.InCallService.VideoCall.Callback {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_telecom_InCallService_VideoCall_Callback(String key) {
        super();
        this.key_ = key;
    }

    @Override
    public void onCallDataUsageChanged(long arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onCallDataUsageChanged", new Object[]{ Long.valueOf(arg0) });
    }

    @Override
    public void onCallSessionEvent(int arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onCallSessionEvent", new Object[]{ Integer.valueOf(arg0) });
    }

    @Override
    public void onCameraCapabilitiesChanged(android.telecom.VideoProfile.CameraCapabilities arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onCameraCapabilitiesChanged", new Object[]{ arg0 });
    }

    @Override
    public void onPeerDimensionsChanged(int arg0, int arg1) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onPeerDimensionsChanged", new Object[]{ Integer.valueOf(arg0), Integer.valueOf(arg1) });
    }

    @Override
    public void onSessionModifyRequestReceived(android.telecom.VideoProfile arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onSessionModifyRequestReceived", new Object[]{ arg0 });
    }

    @Override
    public void onSessionModifyResponseReceived(int arg0, android.telecom.VideoProfile arg1, android.telecom.VideoProfile arg2) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onSessionModifyResponseReceived", new Object[]{ Integer.valueOf(arg0), arg1, arg2 });
    }

    @Override
    public void onVideoQualityChanged(int arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onVideoQualityChanged", new Object[]{ Integer.valueOf(arg0) });
    }

    @Override
    public String toString() {
        return "Adapter_android_telecom_InCallService_VideoCall_Callback[key=" + key_ + "]";
    }

}
