// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.location.LocationListener
// Destination: runtime/java/com/stratum/adapters/Adapter_android_location_LocationListener.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_location_LocationListener implements android.location.LocationListener {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_location_LocationListener(String key) {
        this.key_ = key;
    }

    @Override
    public void onLocationChanged(android.location.Location arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onLocationChanged", new Object[]{ arg0 });
    }

    @Override
    public String toString() {
        return "Adapter_android_location_LocationListener[key=" + key_ + "]";
    }

}
