// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.net.wifi.WifiManager$ScanResultsCallback
// Destination: runtime/java/com/stratum/adapters/Adapter_android_net_wifi_WifiManager_ScanResultsCallback.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_net_wifi_WifiManager_ScanResultsCallback extends android.net.wifi.WifiManager.ScanResultsCallback {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_net_wifi_WifiManager_ScanResultsCallback(String key) {
        super();
        this.key_ = key;
    }

    @Override
    public void onScanResultsAvailable() {
        StratumInvocationHandler.nativeDispatch(
            key_, "onScanResultsAvailable", new Object[0]);
    }

    @Override
    public String toString() {
        return "Adapter_android_net_wifi_WifiManager_ScanResultsCallback[key=" + key_ + "]";
    }

}
