// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.location.GnssStatus$Callback
// Destination: runtime/java/com/stratum/adapters/Adapter_android_location_GnssStatus_Callback.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_location_GnssStatus_Callback extends android.location.GnssStatus.Callback {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_location_GnssStatus_Callback(String key) {
        super();
        this.key_ = key;
    }

    @Override
    public void onFirstFix(int arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onFirstFix", new Object[]{ Integer.valueOf(arg0) });
    }

    @Override
    public void onSatelliteStatusChanged(android.location.GnssStatus arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onSatelliteStatusChanged", new Object[]{ arg0 });
    }

    @Override
    public void onStarted() {
        StratumInvocationHandler.nativeDispatch(
            key_, "onStarted", new Object[0]);
    }

    @Override
    public void onStopped() {
        StratumInvocationHandler.nativeDispatch(
            key_, "onStopped", new Object[0]);
    }

    @Override
    public String toString() {
        return "Adapter_android_location_GnssStatus_Callback[key=" + key_ + "]";
    }

}
