// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.view.View$OnLongClickListener
// Destination: runtime/java/com/stratum/adapters/Adapter_android_view_View_OnLongClickListener.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_view_View_OnLongClickListener implements android.view.View.OnLongClickListener {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_view_View_OnLongClickListener(String key) {
        this.key_ = key;
    }

    @Override
    public boolean onLongClick(android.view.View arg0) {
        Object __r = StratumInvocationHandler.nativeDispatch(
            key_, "onLongClick", new Object[]{ arg0 });
        if (__r == null) { return false; }
        return (__r instanceof Boolean) ? ((Boolean) __r).booleanValue() : (__r instanceof Number && ((Number) __r).intValue() != 0);
    }

    @Override
    public String toString() {
        return "Adapter_android_view_View_OnLongClickListener[key=" + key_ + "]";
    }

}
