// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.telephony.SmsManager$FinancialSmsCallback
// Destination: runtime/java/com/stratum/adapters/Adapter_android_telephony_SmsManager_FinancialSmsCallback.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_telephony_SmsManager_FinancialSmsCallback extends android.telephony.SmsManager.FinancialSmsCallback {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_telephony_SmsManager_FinancialSmsCallback(String key) {
        super();
        this.key_ = key;
    }

    @Override
    public void onFinancialSmsMessages(android.database.CursorWindow arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onFinancialSmsMessages", new Object[]{ arg0 });
    }

    @Override
    public String toString() {
        return "Adapter_android_telephony_SmsManager_FinancialSmsCallback[key=" + key_ + "]";
    }

}
