// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.transition.Transition$EpicenterCallback
// Destination: runtime/java/com/stratum/adapters/Adapter_android_transition_Transition_EpicenterCallback.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_transition_Transition_EpicenterCallback extends android.transition.Transition.EpicenterCallback {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_transition_Transition_EpicenterCallback(String key) {
        super();
        this.key_ = key;
    }

    @Override
    public android.graphics.Rect onGetEpicenter(android.transition.Transition arg0) {
        Object __r = StratumInvocationHandler.nativeDispatch(
            key_, "onGetEpicenter", new Object[]{ arg0 });
        if (__r == null) { return null; }
        return (android.graphics.Rect) __r;
    }

    @Override
    public String toString() {
        return "Adapter_android_transition_Transition_EpicenterCallback[key=" + key_ + "]";
    }

}
