// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source Definition: android.companion.CompanionDeviceManager$Callback
// Destination: runtime/java/com/stratum/adapters/Adapter_android_companion_CompanionDeviceManager_Callback.java
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_companion_CompanionDeviceManager_Callback extends android.companion.CompanionDeviceManager.Callback {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_companion_CompanionDeviceManager_Callback(String key) {
        super();
        this.key_ = key;
    }

    @Override
    public void onAssociationCreated(android.companion.AssociationInfo arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onAssociationCreated", new Object[]{ arg0 });
    }

    @Override
    public void onAssociationPending(android.content.IntentSender arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onAssociationPending", new Object[]{ arg0 });
    }

    @Override
    public void onDeviceFound(android.content.IntentSender arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onDeviceFound", new Object[]{ arg0 });
    }

    @Override
    public void onFailure(CharSequence arg0) {
        StratumInvocationHandler.nativeDispatch(
            key_, "onFailure", new Object[]{ arg0 });
    }

    @Override
    public String toString() {
        return "Adapter_android_companion_CompanionDeviceManager_Callback[key=" + key_ + "]";
    }

}
